export const DELETE_TODO = 'DELETE_TODO';
export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const CHANGE_PRIORITY = 'CHANGE_PRIORITY';
export const SELECT_PRIORITY_FILTER = 'SELECT_PRIORITY_FILTER';
export const SELECT_STATUS_FILTER = 'SELECT_STATUS_FILTER';
